### ISSUE TITLE
Tech-stack verbeteren

### ISSUE THREAD

**Issue by DDuijker** [DDuijker/Swiping-App#123]
- Pyramid principle

Adviseren document
- Eerste Fase 
- Tweede Fase
- Derde Fase
- Vierde Fase

**Comment by MarjonPhu** [comment]
- [ ] Product Vision Board: Op welke manieren wordt er aan de app geld verdient?
- [ ] Mindmaps 'echt' inleveren
- [ ] Tech-stack: betere onderbouwing, betrek b.v. de non-functionals erbij, geen duidelijke aanpak voor bepalen van de keuzes en hoe aan de informatie is gekomen
- [ ] C4-model: staan nog onbekenden: oa. Database en authentication services.  Een database kan geen service aanroepen (C2). Een relatie tussen Componenten kan geen service aanroepen (Authentication service). Denk goed na over welk component de authentication service gaat aanroepen. Hoe ga je de horizontale scaling doen in dit C4 model? En hoe borgen jullie de gebruikersdata? Ook maken jullie gebruik van een externe authenticatie service, maar wordt bij de non-functionals aangegeven dat er sterke wachtwoorden en 
zelfs 2FA plaatsvindt. Dit komt niet in jullie C4 model terug. Neem in het algemeen de non-functionals nog even goed door en kijk hoe je deze kunt/gaat realiseren.
